name: Storybook Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, converted_to_draft, ready_for_review]
    branches: [ main ]
  schedule:
    # Run at midnight PST (8 AM UTC)
    - cron: '0 8 * * *'

jobs:
  test:
    if: github.event.pull_request.draft == true || github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Run Storybook tests
        id: storybook-test
        run: |
          if npm run test-storybook; then
            echo "test_outcome=success" >> "$GITHUB_OUTPUT"
          else
            echo "test_outcome=failure" >> "$GITHUB_OUTPUT"
          fi
        continue-on-error: true

      - name: Send Slack notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "text": "*Storybook Test Results* 📚\n*Repository:* ${{ github.repository }}\n*Status:* ${{ steps.storybook-test.outputs.test_outcome == 'success' && '✅ Passed' || '❌ Failed' }}",
              "attachments": [{
                "color": "${{ steps.storybook-test.outputs.test_outcome == 'success' && 'good' || 'danger' }}"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 